### ISSUE TITLE
feature request: downloading

### ISSUE THREAD

**Issue by teddblue** [windows-server-2003/ThirdTube#102] opened 2022-05-29 00:29 UTC
a method allowing one to download videos and view downloaded videos offline would be nice

**Comment by CSab6482** [comment] 2022-05-29 06:56
This is an interesting ticket. I personally use https://9convert.com to download YouTube videos, and it even works for age restricted videos (may be useful for #87). Hopefully this is possible to implement!

**Comment by windows-server-2003** [comment] 2022-06-06 05:05
duplicate of #48

**Closed by windows-server-2003** 2022-06-06 05:05 UTC
