### ISSUE TITLE
(Feature Request) Logging in with google

### ISSUE THREAD

**Issue by HorusDaCat** [windows-server-2003/ThirdTube#95] opened 2022-05-12 02:14 UTC
I am not sure how feasible this is but logging in to youtube would be a nice feature, to have the ability to access age restrcted content, comment, that kinda stuff.

**Comment by Minionguyjpro** [comment] 2022-05-12 14:34
Take a look at issue #71

**Comment by windows-server-2003** [comment] 2022-05-25 09:47
At least, it's a duplicate of #71 as @Minionguyjpro said.

**Closed by windows-server-2003** 2022-05-25 09:47 UTC
