### ISSUE TITLE
Feature Request: Loop video

### ISSUE THREAD

**Issue by AltyKog** [windows-server-2003/ThirdTube#156] opened 2023-01-08 04:36 UTC
I use this app to listen to music a lot since my 2DS is the only thing with a headphone jack to connect to but I find myself having to physically go back and restart videos which can be a bit of a hassle when I'm on the move or I'm busy. Ofc no pressure, just a quality of life request to add a loop video setting

**Comment by windows-server-2003** [comment] 2023-01-20 02:58
Duplicate of #26

**Closed by windows-server-2003** 2023-01-20 02:58 UTC
