### ISSUE TITLE
Use Return YouTube Dislike analytics to bring the dislike counter back

### ISSUE THREAD

**Issue by bimmy4664** [windows-server-2003/ThirdTube#116] opened 2022-08-14 11:30 UTC

**Comment by SleepyBoi2852** [comment] 2022-08-17 23:53
I Love this idea. Also, since "Return Youtube Dislike" has an API, it shouldn't be that hard to implement it.

**Comment by windows-server-2003** [comment] 2022-08-19 08:01
Duplicate of #91
Although it is implementable, I'm not planning to implement things on third-party services.

**Closed by windows-server-2003** 2022-08-19 08:01 UTC
