### ISSUE TITLE
Crashes after searching for certain channels 

### ISSUE THREAD

**Issue by x-industries-uk** [windows-server-2003/ThirdTube#145] opened 2022-12-18 19:13 UTC
When searching for certain channels (notable EmKay and Mental Outlaw), the app just crashes. I am using an old 3DS, however, so that may have something to do with it.

**Comment by windows-server-2003** [comment] 2022-12-25 07:14
Could you provide with some information of how to reproduce the issue?

**Comment by x-industries-uk** [comment] 2022-12-25 11:52
On the **old** 3DS, open the app (installed as a CIA, not a 3DSX) and search for "emkay". Then tap on the channel with a hand as the icon.

Unless I've just got a dodgy install, the app should immediately crash.

**Comment by windows-server-2003** [comment] 2022-12-26 07:33
I could not reproduce the issue on my side.
Can you try this build and compare with v0.5.1 to see if you can be sure the bug is fixed in this build?

[ThirdTube.zip](https://github.com/windows-server-2003/ThirdTube/files/10302184/ThirdTube.zip)

**Comment by x-industries-uk** [comment] 2022-12-26 16:07
That seems to have fixed the bug, as well as improved my experience overall! Thank you, well done, and I hope you had a very merry xmas!

**Closed** 2022-12-26 16:08 UTC
